### ISSUE TITLE
[SEVERE] #VALUE! error in spreadsheet. Affects public website.

### ISSUE THREAD

**Issue by Manit100** [COVID19Tracking/covid-tracking#13]
There is a formula error somewhere on your tracking Google Sheet. This unknown error manifests as a #VALUE error on the "US Current" sheet. See screenshot below.
![Google Sheet - US Current](https://user-images.githubusercontent.com/62500480/77246693-578ef880-6c5c-11ea-809f-8f3d1a71da42.png)

_______________________________________
The national summary table in the "Most Recent Data" section of the public website (https://covidtracking.com/data/) also shows a blank. See screenshot below. In my experience, this is likely because of the above #VALUE error. 
![Website - Most Recent Data](https://user-images.githubusercontent.com/62500480/77246694-58c02580-6c5c-11ea-9580-6acd5fe4599e.png)

_______________________________________

Should be an easy fix (<5 minutes) but needs to be done ASAP since your website is probably the best source of tracking Covid-19 data in the country. (Kudos, btw!)

PS - Couldn't find any way to contact you through your website. Might want to add a quick form for such issues?

**Comment by shils** [comment]
This appears to have been fixed.

**Comment by joshellington** [comment]
Yes, thank you for the heads up @shils!
