### ISSUE TITLE
JSON enpoint for google sheet data

### ISSUE THREAD

**Issue by webmasterkai** [COVID19Tracking/covid-tracking#2]
It'd be great to have an easily accessible URL that returns some json data. Is the sheet ID spreadsheetID `18oVRrHj3c183mHmq3m89_163yuYltLNlOmPerQ18E8w`? I think the Google API also needs individual sheet ids. I think the most important sheet is the "States daily 4 pm ET" since most of the other data can be calculated from there. Happen to know the sheet id for that one?

I'll poke around a bit later today to see if I can get the Sheets API to spit something out. From there I was thinking a cached proxy (maybe Cloudflare workers) or a simple curl request that posts to some CDN.

Actually, I see that https://github.com/COVID19Tracking/covid-19-crawler has some CSV files! I'll start there and write up some documentation with options for easy API consumption. It looks like it might be missing some of the earlier daily data from the 

Also, now I see https://github.com/huuep/coronavirusapi

Thanks!

**Comment by hammer** [comment]
@webmasterkai please do experiment with a way to export our data as JSON! Our data is different from that at coronavirusapi.

**Comment by webmasterkai** [comment]
Okay, I created a Cloudflare Worker that makes a requests to get the sheet info and then cleans it up a bit and returns an array of values. I'm not sure the easiest way to get it hosted on your domain. Open to ideas.

## Initial Basic API - JSON Endpoints

* States current - https://covid.cape.io/states
* States daily 4 pm ET - https://covid.cape.io/states/daily
* States info - https://covid.cape.io/states/info
* US current - https://covid.cape.io/us
* US daily - https://covid.cape.io/us/daily
* Counties- https://covid.cape.io/counties

**Comment by joshellington** [comment]
Nice, @webmasterkai! This is a great start. Couple questions/considerations (apologies, not very familiar with CF workers yet):

- Does each request to covid.cape.io/* trigger a request to the Google Sheet? If not, what does the TTL/expires time look like for their proxy caching?
- Which sheet "endpoint" are the workers hitting? `/htmlview` or something else?
- Is the CF workers code on Github yet? Easily deployable currently or in the future by multiple folks?

Main priorities at this point IMO are flexibility both in rapidly responding to data formatting changes, super high availability, and ability to distribute both ongoing development and deployments.

Again, thanks so much for putting these together! Getting this data in machine-readable, highly available format will be great 👍

**Comment by webmasterkai** [comment]
* Yes, each trigger is making a request to Google Sheets. A TTL can be configured if needed. Usage is being applied to my google dev acct.
* Google Sheets Endpoint: `https://sheets.googleapis.com/v4/spreadsheets/${worksheetId}/values/${sheetName}?key=${key}` More info: https://developers.google.com/sheets/api/
* Code/Repo located here: I https://github.com/cape-io/covid-tracking-api Happy to transfer repo ownership.

Happy to help.

**Comment by hammer** [comment]
@webmasterkai awesome thanks! I will add you to the org now so that you can transfer ownership yourself.

**Comment by hammer** [comment]
Solved! https://github.com/COVID19Tracking/covid-tracking-api
