### ISSUE TITLE
New URL for CT

### ISSUE THREAD

**Issue by SGaul-OPM** [COVID19Tracking/covid-tracking#50]
A few weeks ago, we started posting COVID data for CT to our state's open data portal, to give an option besides the PDF documents. It might be easier for you to pull from there. The datasets are posted to a dashboard here: https://data.ct.gov/coronavirus, which links to the individual datasets on our state's open data platform (through Socrata). 

We will continue to keep these datasets updated daily; the daily PDF updates via the state portal may switch to lower frequency in the future. We're also planning to add new data, including race / ethnicity, to the portal next week. 

You can also email me at scott.gaul@ct.gov with any questions.

**Comment by zachlipton** [comment]
Thanks so much for reaching out! We really appreciate it—I believe you're the first state to proactively get in touch and make sure we're using the right data, which has made us all so happy. I'm thrilled to hear race/ethnicity data is coming; we have a team that's starting to track and aggregate that now. 

Our data entry team just updated the URL to use your dashboard, and it looks like we're already monitoring your API to alert us about new testing data. I passed your contact on to our editors in case there are any questions that come up in the future.

Greatly appreciate you letting us know. Thanks for all you do!

**Comment by SGaul-OPM** [comment]
Thank you! We've used the best practices documents and examples from other states from your site, so it's a helpful resource for us. One more thing - can you change the language that has CT as 'posting data only in a PDF' - we are still using the PDF reports, but moving to have all or most of the data from those replicated in machine-readable format. I saw something else about county data feeds - for ex. those are accessible via: https://data.ct.gov/Health-and-Human-Services/COVID-19-confirmed-cases-by-county-/bfnu-rgqt
