### ISSUE TITLE
Colorado URL needs to be updated

### ISSUE THREAD

**Issue by gafortiby** [COVID19Tracking/covid-tracking#9]
Colorado changed where the data is kept and reported. Here is the new URL
https://data-cdphe.opendata.arcgis.com/datasets/colorado-covid-19-positive-cases-by-county-of-identification

I don't know how ARCGIS works, but it appears that you can get a CSV from here. (Note that some positive cases have unknown exact location so it does not belong to any county. so total summed across all counties does not match total of the state.
https://opendata.arcgis.com/datasets/46c727cc29424b1fb9db67554c7df04e_0.csv?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D

**Comment by gafortiby** [comment]
This might work better, it returns the total positive for the state. (The state is only reporting Positives from now on)

https://services3.arcgis.com/66aUo8zsujfVXRIT/ArcGIS/rest/services/Cases_by_County/FeatureServer/0/query?objectIds=1&outFields=State_Number_Positive_Cases_Tot&f=html&returnGeometry=false

**Comment by zachlipton** [comment]
Fixed in https://github.com/COVID19Tracking/covid-tracking/commit/bb4c9a228edc61354f32681febc3088826ffb7fa
